2024-12-19T21:42:04.242Z [[31merror[39m]: Incorrect number of arguments for PROCEDURE pycash-db.create_user; expected 7, got 6
2024-12-19T21:42:51.062Z [[31merror[39m]: Incorrect number of arguments for PROCEDURE pycash-db.create_user; expected 7, got 6
2024-12-19T21:49:24.241Z [[31merror[39m]: Duplicate entry 'ejemplo@ejemplo.mx' for key 'users.email'
